// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Todo struct {
	ID          string
	Title       string
	Description sql.NullString
	Completed   sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
